# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  customer_image:  # id of input
    description: 'Docker image to scan'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.customer_image }}