# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  customer_image:  # id of input
    description: 'Docker image to scan'
    required: true
outputs:
  findings: # id of output
    description: 'The findings output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  options: --user root
  args:
    - ${{ inputs.customer_image }}