on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: An example customer workflow
    steps:
      # Represent the customer building their own image
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t "${{ github.event.repository.name }}:latest" .
      - name: Docker Image SBOM
        uses: anchore/sbom-action@v0
        with:
          image: "${{ github.event.repository.name }}:latest"
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
      - name: Print the SBOM
        run: cat "${{ github.event.repository.name }}-sbom.spdx.json"
      - name: Scan SBOM
        uses: anchore/scan-action@v3
        id: scan
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: false
      - name: Print SARIF
        run: cat ${{ steps.scan.outputs.sarif }}
      # To be replaced -- imagecov's action    
      - name: Hello world action step
        id: hello
        uses: imagecov/imagecov-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"